sudo: required
dist: trusty
language: go
go:
  - 1.5

env:
  matrix:
    - TEST_SUITE="--static"
    - TEST_SUITE="--unit-go"

install:
  - echo "Skip. Install is done by the test script."
script: sh -v ./run-checks $TEST_SUITE
