name: snappyd
source: lp:clapper
description: Manage a system with a snappy webui
version: 0.2.11
architecture: amd64
frameworks: ubuntu-core-15.04-dev1
integration:
        snappyd:
                apparmor-profile: meta/snappyd.apparmor
services:
        - name: snappyd
          start: snappyd
          description: Manage your device
ports: 
    required: 8080
maintainer: Clapping Team
icon: meta/clap.png
