name: webdm
source: lp:clapper
description: Manage a system with a snappy webui
version: 0.4
architecture: UNKNOWN_ARCH
frameworks: ubuntu-core-15.04-dev1
integration:
        snappyd:
                apparmor-profile: meta/snappyd.apparmor
services:
        - name: snappyd
          start: snappyd
          description: Snappy WebDM
ports: 
    required: 8080
maintainer: Clapping Team
icon: meta/clap.png
