name: webdm
source: lp:webdm
description: Manage a system with a snappy webui
version: 0.3
type: framework
architecture: UNKNOWN_ARCH
integration:
    framework:
        framework: meta/webdm.framework
    snappyd:
        apparmor-profile: meta/snappyd.apparmor
    avahi:
        apparmor-profile: meta/avahi.apparmor
services:
    - name: snappyd
      start: snappyd
      description: Snappy WebDM
      ports:
          external:
              ui:
                  port: 4200/tcp
                  negotiable: false
    - name: avahi
      start: avahi-daemon
      description: Avahi daemon
vendor: Sergio Schvezov <sergio.schvezov@canonical.com>
icon: meta/clap.png
