name: webdm
source: lp:webdm
description: Manage a system with a snappy webui
version: 0.1
type: framework
architecture: UNKNOWN_ARCH
frameworks: ubuntu-core-15.04-dev1
integration:
    framework:
        framework: meta/webdm.framework
    snappyd:
        apparmor-profile: meta/snappyd.apparmor
    avahi:
        apparmor-profile: meta/avahi.apparmor
services:
    - name: snappyd
      start: snappyd
      description: Snappy WebDM
    - name: avahi
      start: avahi-daemon -f avahi-daemon.conf
      description: Avahi daemon
ports:
    required: 4200
maintainer: Sergio Schvezov <sergio.schvezov@canonical.com>
icon: meta/clap.png
