name: webdm
vendor: Sergio Schvezov <sergio.schvezov@canonical.com>
icon: meta/webdm-icon.png
source: lp:webdm
type: framework
version: 0.11.1
architecture: UNKNOWN_ARCH
services:
    - name: snappyd
      start: snappyd
      description: Snappy WebDM
      ports:
          external:
              ui:
                  port: 4200/tcp
                  negotiable: false
      security-policy:
          apparmor: meta/snappyd.profile
          seccomp: meta/snappyd.seccomp
